# Generated by Django 3.2.5 on 2021-07-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('part', models.CharField(max_length=20)),
                ('demand', models.TextField(max_length=200)),
                ('time', models.DateField()),
            ],
        ),
    ]
